"""phase3 foundation: dine-in table, table status, notifications

Revision ID: 2a5a2362287c
Revises: 88239fbc4dd9
Create Date: 2026-07-29 09:46:48.438143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2a5a2362287c'
down_revision: Union[str, None] = '88239fbc4dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ALTER TYPE ... ADD VALUE cannot run inside Postgres's implicit
    # transaction block, so it needs its own autocommit block — same
    # mechanics as the waiter/chef roleenum migration.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE fulfillmenttype ADD VALUE IF NOT EXISTS 'dine_in'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_email', sa.String(length=150), nullable=True),
    sa.Column('recipient_phone', sa.String(length=30), nullable=True),
    sa.Column('channel', sa.Enum('email', 'sms', name='notificationchannel'), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', name='notificationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('table_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'restaurant_tables', ['table_id'], ['id'])

    # add_column (unlike create_table) doesn't auto-create a new inline enum
    # type, so it must be created explicitly first.
    table_status_enum = sa.Enum('free', 'occupied', 'reserved', name='tablestatus')
    table_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('restaurant_tables', sa.Column('status', table_status_enum, nullable=False, server_default='free'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurant_tables', 'status')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'table_id')
    op.drop_table('notification_logs')
    # ### end Alembic commands ###
    # PostgreSQL cannot remove a value from an existing enum type (no ALTER
    # TYPE ... DROP VALUE) — 'dine_in' stays on fulfillmenttype permanently.
    raise NotImplementedError(
        "Cannot fully downgrade: PostgreSQL does not support removing enum "
        "values ('dine_in' from fulfillmenttype). Manual intervention required."
    )
