"""stripe_connect_and_subscriptions

Revision ID: 59d7a568862f
Revises: 749b21e66ad2
Create Date: 2026-07-30 14:40:12.722028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '59d7a568862f'
down_revision: Union[str, None] = '749b21e66ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('stripe_account_id', sa.String(length=255), nullable=True))
    op.add_column('businesses', sa.Column('stripe_charges_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('businesses', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('businesses', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.add_column('businesses', sa.Column('subscription_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'subscription_status')
    op.drop_column('businesses', 'stripe_subscription_id')
    op.drop_column('businesses', 'stripe_customer_id')
    op.drop_column('businesses', 'stripe_charges_enabled')
    op.drop_column('businesses', 'stripe_account_id')
    # ### end Alembic commands ###
