"""multi_tenancy_foundation

Revision ID: 749b21e66ad2
Revises: 2a5a2362287c
Create Date: 2026-07-30 12:32:12.792058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '749b21e66ad2'
down_revision: Union[str, None] = '2a5a2362287c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('currency_symbol', sa.String(length=10), nullable=False),
    sa.Column('default_vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('receipt_footer', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_slug'), 'businesses', ['slug'], unique=True)

    # Seed the one existing business from the old business_settings singleton
    # (falls back to sane defaults if that row was never created), so every
    # pre-existing row across the schema has a real tenant to backfill onto.
    connection = op.get_bind()
    existing = connection.execute(
        sa.text("SELECT address, currency_symbol, default_vat_rate, receipt_footer FROM business_settings WHERE id = 1")
    ).fetchone()
    address, currency_symbol, default_vat_rate, receipt_footer = existing if existing else (None, "$", 0, "Thank you!")

    businesses_table = sa.table(
        'businesses',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
        sa.column('slug', sa.String),
        sa.column('address', sa.String),
        sa.column('currency_symbol', sa.String),
        sa.column('default_vat_rate', sa.Numeric),
        sa.column('receipt_footer', sa.String),
    )
    business_id = connection.execute(
        businesses_table.insert().values(
            name="Bavaria Genuss Restaurant",
            slug="bavaria-genuss",
            address=address,
            currency_symbol=currency_symbol,
            default_vat_rate=default_vat_rate,
            receipt_footer=receipt_footer,
        ).returning(businesses_table.c.id)
    ).scalar()

    op.drop_table('business_settings')
    op.add_column('audit_logs', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_audit_logs_business_id'), 'audit_logs', ['business_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('brands', sa.Column('business_id', sa.Integer(), nullable=True))
    op.drop_constraint('brands_name_key', 'brands', type_='unique')
    op.create_index(op.f('ix_brands_business_id'), 'brands', ['business_id'], unique=False)
    op.create_unique_constraint('uq_brands_business_name', 'brands', ['business_id', 'name'])
    op.create_foreign_key(None, 'brands', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('categories', sa.Column('business_id', sa.Integer(), nullable=True))
    op.drop_constraint('categories_name_key', 'categories', type_='unique')
    op.create_index(op.f('ix_categories_business_id'), 'categories', ['business_id'], unique=False)
    op.create_unique_constraint('uq_categories_business_name', 'categories', ['business_id', 'name'])
    op.create_foreign_key(None, 'categories', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('customers', sa.Column('business_id', sa.Integer(), nullable=True))
    op.drop_index('ix_customers_email_login_unique', table_name='customers', postgresql_where='(password_hash IS NOT NULL)')
    op.create_index('ix_customers_email_login_unique', 'customers', ['business_id', 'email'], unique=True, postgresql_where=sa.text('password_hash IS NOT NULL'))
    op.create_index(op.f('ix_customers_business_id'), 'customers', ['business_id'], unique=False)
    op.create_foreign_key(None, 'customers', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('discounts', sa.Column('business_id', sa.Integer(), nullable=True))
    op.drop_index('ix_discounts_code', table_name='discounts')
    op.create_index(op.f('ix_discounts_code'), 'discounts', ['code'], unique=False)
    op.create_index(op.f('ix_discounts_business_id'), 'discounts', ['business_id'], unique=False)
    op.create_unique_constraint('uq_discounts_business_code', 'discounts', ['business_id', 'code'])
    op.create_foreign_key(None, 'discounts', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('expenses', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_expenses_business_id'), 'expenses', ['business_id'], unique=False)
    op.create_foreign_key(None, 'expenses', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('held_sales', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_held_sales_business_id'), 'held_sales', ['business_id'], unique=False)
    op.create_foreign_key(None, 'held_sales', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('inventory', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_inventory_business_id'), 'inventory', ['business_id'], unique=False)
    op.create_foreign_key(None, 'inventory', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('newsletter_subscribers', sa.Column('business_id', sa.Integer(), nullable=True))
    op.drop_index('ix_newsletter_subscribers_email', table_name='newsletter_subscribers')
    op.create_index(op.f('ix_newsletter_subscribers_email'), 'newsletter_subscribers', ['email'], unique=False)
    op.create_index(op.f('ix_newsletter_subscribers_business_id'), 'newsletter_subscribers', ['business_id'], unique=False)
    op.create_unique_constraint('uq_newsletter_business_email', 'newsletter_subscribers', ['business_id', 'email'])
    op.create_foreign_key(None, 'newsletter_subscribers', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('notification_logs', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_notification_logs_business_id'), 'notification_logs', ['business_id'], unique=False)
    op.create_foreign_key(None, 'notification_logs', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('order_items', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_order_items_business_id'), 'order_items', ['business_id'], unique=False)
    op.create_foreign_key(None, 'order_items', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('orders', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_business_id'), 'orders', ['business_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('products', sa.Column('business_id', sa.Integer(), nullable=True))
    op.drop_index('ix_products_sku', table_name='products')
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_index(op.f('ix_products_business_id'), 'products', ['business_id'], unique=False)
    op.create_unique_constraint('uq_products_business_sku', 'products', ['business_id', 'sku'])
    op.create_foreign_key(None, 'products', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('purchase_items', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_purchase_items_business_id'), 'purchase_items', ['business_id'], unique=False)
    op.create_foreign_key(None, 'purchase_items', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('purchase_payments', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_purchase_payments_business_id'), 'purchase_payments', ['business_id'], unique=False)
    op.create_foreign_key(None, 'purchase_payments', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('purchase_return_items', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_purchase_return_items_business_id'), 'purchase_return_items', ['business_id'], unique=False)
    op.create_foreign_key(None, 'purchase_return_items', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('purchase_returns', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_purchase_returns_business_id'), 'purchase_returns', ['business_id'], unique=False)
    op.create_foreign_key(None, 'purchase_returns', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('purchases', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_purchases_business_id'), 'purchases', ['business_id'], unique=False)
    op.create_foreign_key(None, 'purchases', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('refund_items', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_refund_items_business_id'), 'refund_items', ['business_id'], unique=False)
    op.create_foreign_key(None, 'refund_items', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('refunds', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_refunds_business_id'), 'refunds', ['business_id'], unique=False)
    op.create_foreign_key(None, 'refunds', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('reservations', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_reservations_business_id'), 'reservations', ['business_id'], unique=False)
    op.create_foreign_key(None, 'reservations', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('restaurant_tables', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_restaurant_tables_business_id'), 'restaurant_tables', ['business_id'], unique=False)
    op.create_foreign_key(None, 'restaurant_tables', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('reviews', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_reviews_business_id'), 'reviews', ['business_id'], unique=False)
    op.create_foreign_key(None, 'reviews', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('stock_movements', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stock_movements_business_id'), 'stock_movements', ['business_id'], unique=False)
    op.create_foreign_key(None, 'stock_movements', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('stock_transfers', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stock_transfers_business_id'), 'stock_transfers', ['business_id'], unique=False)
    op.create_foreign_key(None, 'stock_transfers', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('stores', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stores_business_id'), 'stores', ['business_id'], unique=False)
    op.create_foreign_key(None, 'stores', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('suppliers', sa.Column('business_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_suppliers_business_id'), 'suppliers', ['business_id'], unique=False)
    op.create_foreign_key(None, 'suppliers', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('units', sa.Column('business_id', sa.Integer(), nullable=True))
    op.drop_constraint('units_name_key', 'units', type_='unique')
    op.create_index(op.f('ix_units_business_id'), 'units', ['business_id'], unique=False)
    op.create_unique_constraint('uq_units_business_name', 'units', ['business_id', 'name'])
    op.create_foreign_key(None, 'units', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('business_id', sa.Integer(), nullable=True))
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_business_id'), 'users', ['business_id'], unique=False)
    op.create_unique_constraint('uq_users_business_email', 'users', ['business_id', 'email'])
    op.create_foreign_key(None, 'users', 'businesses', ['business_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

    # Backfill every pre-existing row onto the single seeded business, then
    # tighten business_id to NOT NULL now that no row is left null.
    tenant_scoped_tables = [
        'audit_logs', 'brands', 'categories', 'customers', 'discounts', 'expenses',
        'held_sales', 'inventory', 'newsletter_subscribers', 'notification_logs',
        'order_items', 'orders', 'products', 'purchase_items', 'purchase_payments',
        'purchase_return_items', 'purchase_returns', 'purchases', 'refund_items',
        'refunds', 'reservations', 'restaurant_tables', 'reviews', 'stock_movements',
        'stock_transfers', 'stores', 'suppliers', 'units', 'users',
    ]
    for table in tenant_scoped_tables:
        op.execute(sa.text(f"UPDATE {table} SET business_id = :bid").bindparams(bid=business_id))
        op.alter_column(table, 'business_id', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint('uq_users_business_email', 'users', type_='unique')
    op.drop_index(op.f('ix_users_business_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_column('users', 'business_id')
    op.drop_constraint(None, 'units', type_='foreignkey')
    op.drop_constraint('uq_units_business_name', 'units', type_='unique')
    op.drop_index(op.f('ix_units_business_id'), table_name='units')
    op.create_unique_constraint('units_name_key', 'units', ['name'])
    op.drop_column('units', 'business_id')
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_index(op.f('ix_suppliers_business_id'), table_name='suppliers')
    op.drop_column('suppliers', 'business_id')
    op.drop_constraint(None, 'stores', type_='foreignkey')
    op.drop_index(op.f('ix_stores_business_id'), table_name='stores')
    op.drop_column('stores', 'business_id')
    op.drop_constraint(None, 'stock_transfers', type_='foreignkey')
    op.drop_index(op.f('ix_stock_transfers_business_id'), table_name='stock_transfers')
    op.drop_column('stock_transfers', 'business_id')
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_index(op.f('ix_stock_movements_business_id'), table_name='stock_movements')
    op.drop_column('stock_movements', 'business_id')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_index(op.f('ix_reviews_business_id'), table_name='reviews')
    op.drop_column('reviews', 'business_id')
    op.drop_constraint(None, 'restaurant_tables', type_='foreignkey')
    op.drop_index(op.f('ix_restaurant_tables_business_id'), table_name='restaurant_tables')
    op.drop_column('restaurant_tables', 'business_id')
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_index(op.f('ix_reservations_business_id'), table_name='reservations')
    op.drop_column('reservations', 'business_id')
    op.drop_constraint(None, 'refunds', type_='foreignkey')
    op.drop_index(op.f('ix_refunds_business_id'), table_name='refunds')
    op.drop_column('refunds', 'business_id')
    op.drop_constraint(None, 'refund_items', type_='foreignkey')
    op.drop_index(op.f('ix_refund_items_business_id'), table_name='refund_items')
    op.drop_column('refund_items', 'business_id')
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_index(op.f('ix_purchases_business_id'), table_name='purchases')
    op.drop_column('purchases', 'business_id')
    op.drop_constraint(None, 'purchase_returns', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_returns_business_id'), table_name='purchase_returns')
    op.drop_column('purchase_returns', 'business_id')
    op.drop_constraint(None, 'purchase_return_items', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_return_items_business_id'), table_name='purchase_return_items')
    op.drop_column('purchase_return_items', 'business_id')
    op.drop_constraint(None, 'purchase_payments', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_payments_business_id'), table_name='purchase_payments')
    op.drop_column('purchase_payments', 'business_id')
    op.drop_constraint(None, 'purchase_items', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_items_business_id'), table_name='purchase_items')
    op.drop_column('purchase_items', 'business_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint('uq_products_business_sku', 'products', type_='unique')
    op.drop_index(op.f('ix_products_business_id'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.create_index('ix_products_sku', 'products', ['sku'], unique=True)
    op.drop_column('products', 'business_id')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_business_id'), table_name='orders')
    op.drop_column('orders', 'business_id')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_index(op.f('ix_order_items_business_id'), table_name='order_items')
    op.drop_column('order_items', 'business_id')
    op.drop_constraint(None, 'notification_logs', type_='foreignkey')
    op.drop_index(op.f('ix_notification_logs_business_id'), table_name='notification_logs')
    op.drop_column('notification_logs', 'business_id')
    op.drop_constraint(None, 'newsletter_subscribers', type_='foreignkey')
    op.drop_constraint('uq_newsletter_business_email', 'newsletter_subscribers', type_='unique')
    op.drop_index(op.f('ix_newsletter_subscribers_business_id'), table_name='newsletter_subscribers')
    op.drop_index(op.f('ix_newsletter_subscribers_email'), table_name='newsletter_subscribers')
    op.create_index('ix_newsletter_subscribers_email', 'newsletter_subscribers', ['email'], unique=True)
    op.drop_column('newsletter_subscribers', 'business_id')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_business_id'), table_name='inventory')
    op.drop_column('inventory', 'business_id')
    op.drop_constraint(None, 'held_sales', type_='foreignkey')
    op.drop_index(op.f('ix_held_sales_business_id'), table_name='held_sales')
    op.drop_column('held_sales', 'business_id')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_business_id'), table_name='expenses')
    op.drop_column('expenses', 'business_id')
    op.drop_constraint(None, 'discounts', type_='foreignkey')
    op.drop_constraint('uq_discounts_business_code', 'discounts', type_='unique')
    op.drop_index(op.f('ix_discounts_business_id'), table_name='discounts')
    op.drop_index(op.f('ix_discounts_code'), table_name='discounts')
    op.create_index('ix_discounts_code', 'discounts', ['code'], unique=True)
    op.drop_column('discounts', 'business_id')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_index(op.f('ix_customers_business_id'), table_name='customers')
    op.drop_index('ix_customers_email_login_unique', table_name='customers', postgresql_where=sa.text('password_hash IS NOT NULL'))
    op.create_index('ix_customers_email_login_unique', 'customers', ['email'], unique=True, postgresql_where='(password_hash IS NOT NULL)')
    op.drop_column('customers', 'business_id')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint('uq_categories_business_name', 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_business_id'), table_name='categories')
    op.create_unique_constraint('categories_name_key', 'categories', ['name'])
    op.drop_column('categories', 'business_id')
    op.drop_constraint(None, 'brands', type_='foreignkey')
    op.drop_constraint('uq_brands_business_name', 'brands', type_='unique')
    op.drop_index(op.f('ix_brands_business_id'), table_name='brands')
    op.create_unique_constraint('brands_name_key', 'brands', ['name'])
    op.drop_column('brands', 'business_id')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_business_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'business_id')
    op.create_table('business_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('business_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('currency_symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('default_vat_rate', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False),
    sa.Column('receipt_footer', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='business_settings_pkey')
    )
    op.drop_index(op.f('ix_businesses_slug'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
